/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardTransactionsRouteImport } from './routes/_dashboard/transactions'
import { Route as DashboardRecurringBillsRouteImport } from './routes/_dashboard/recurring-bills'
import { Route as DashboardPotsRouteImport } from './routes/_dashboard/pots'
import { Route as DashboardBudgetsRouteImport } from './routes/_dashboard/budgets'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRecurringBillsRoute = DashboardRecurringBillsRouteImport.update({
  id: '/recurring-bills',
  path: '/recurring-bills',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPotsRoute = DashboardPotsRouteImport.update({
  id: '/pots',
  path: '/pots',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBudgetsRoute = DashboardBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/budgets': typeof DashboardBudgetsRoute
  '/pots': typeof DashboardPotsRoute
  '/recurring-bills': typeof DashboardRecurringBillsRoute
  '/transactions': typeof DashboardTransactionsRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/budgets': typeof DashboardBudgetsRoute
  '/pots': typeof DashboardPotsRoute
  '/recurring-bills': typeof DashboardRecurringBillsRoute
  '/transactions': typeof DashboardTransactionsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/_dashboard/budgets': typeof DashboardBudgetsRoute
  '/_dashboard/pots': typeof DashboardPotsRoute
  '/_dashboard/recurring-bills': typeof DashboardRecurringBillsRoute
  '/_dashboard/transactions': typeof DashboardTransactionsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/budgets'
    | '/pots'
    | '/recurring-bills'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/budgets'
    | '/pots'
    | '/recurring-bills'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/design-system'
    | '/_dashboard/budgets'
    | '/_dashboard/pots'
    | '/_dashboard/recurring-bills'
    | '/_dashboard/transactions'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/transactions': {
      id: '/_dashboard/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/recurring-bills': {
      id: '/_dashboard/recurring-bills'
      path: '/recurring-bills'
      fullPath: '/recurring-bills'
      preLoaderRoute: typeof DashboardRecurringBillsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/pots': {
      id: '/_dashboard/pots'
      path: '/pots'
      fullPath: '/pots'
      preLoaderRoute: typeof DashboardPotsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/budgets': {
      id: '/_dashboard/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof DashboardBudgetsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardBudgetsRoute: typeof DashboardBudgetsRoute
  DashboardPotsRoute: typeof DashboardPotsRoute
  DashboardRecurringBillsRoute: typeof DashboardRecurringBillsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBudgetsRoute: DashboardBudgetsRoute,
  DashboardPotsRoute: DashboardPotsRoute,
  DashboardRecurringBillsRoute: DashboardRecurringBillsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
